Add controllers
avan-es/java-shareit pull request #1
Opened 2023-03-02 21:07 UTC by avan-es

Привет! Выполнил ТЗ к спринту 13.

2023-03-03 08:39 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Но есть некоторые замечания, которые необходимо исправить!!!

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/exeptions/ErrorResponse.java
> +    String description;
Модификаторы доступа нужны, в том числе `final`

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/exeptions/ErrorResponse.java
> +public class ErrorResponse {
И самому классу тоже не помешает модификатор `final`

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/model/ItemMapper.java
> +public class ItemMapper {
Советую для этого использовать `enum`

https://www.geeksforgeeks.org/advantages-and-disadvantages-of-using-enum-as-singleton-in-java/

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +    private Matcher matcher;
Зачем для этого поле заводить?
Нельзя обойтись локальной переменной?

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +    }
Может можно сразу `Pattern` скомпилировать?
И тоже его статическим сделать?

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +        return matcher.matches();
Это можно в одну строку переписать:

```java
return pattern.matcher(hex).matches();
```

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +                    .contains(user.getEmail())) {
`contains` в `List` происходит за `O(n)`, а в `Set` за `O(1)` это существенное различие в скорости

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +                            .contains(user.getEmail())) {
аналогично про `contains`

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +    public void emailValidation(UserDto user) {
в этом методе и методе ниже часть кода повторяется, его можно вынести в отдельный метод и переиспользовать

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +                .anyMatch(user -> user.getId().equals(userId))) {
Стоит использовать метод `getUserById` это лучше с точки зрения производительности

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        userValidation.emailIsFree(userDto);
сначала валидация, потом действия, не вперемешку

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepository.java
> +    private final List<User> users = new ArrayList<>();
Хранить все это дело стоит с помощью `Map`

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/model/UserMapper.java
> +public class UserMapper {
Аналогично про `enum`

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/validation/ItemValidation.java
> +public class ItemValidation {
Замечания аналогичные `UservValidation`

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +    private final List<Item> items = new ArrayList<>();
Хранить в `Map`

2023-03-03 08:39 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            throw new ModelValidationException(String.format("Не указан владелиц для '%s'.", item.getName()));
Очень странная последовательность действий, сначала разрешили параметру быть опциональным, а потом бросили исключения, потому что он не заполнен

2023-03-03 10:36 UTC, avan-es commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepository.java
> +    private final List<User> users = new ArrayList<>();
Исправил.

2023-03-03 10:37 UTC, avan-es commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +    private final List<Item> items = new ArrayList<>();
Исправил.

2023-03-03 10:41 UTC, avan-es commented on src/main/java/ru/practicum/shareit/exeptions/ErrorResponse.java
> +    String description;
Добавил.

2023-03-03 10:42 UTC, avan-es commented on src/main/java/ru/practicum/shareit/exeptions/ErrorResponse.java
> +public class ErrorResponse {
Добавил.

2023-03-03 12:31 UTC, avan-es commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +        return matcher.matches();
Исправил.

2023-03-03 12:33 UTC, avan-es commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +    }
Исправил.

2023-03-03 12:34 UTC, avan-es commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +    private Matcher matcher;
Исправил.

2023-03-03 12:35 UTC, avan-es commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +                    .contains(user.getEmail())) {
Исправил.

2023-03-03 12:35 UTC, avan-es commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +                            .contains(user.getEmail())) {
Исправил.

2023-03-03 13:00 UTC, avan-es commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +    public void emailValidation(UserDto user) {
Исправил.

2023-03-03 13:02 UTC, avan-es commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +                .anyMatch(user -> user.getId().equals(userId))) {
Исправил.

2023-03-03 13:05 UTC, avan-es commented on src/main/java/ru/practicum/shareit/item/validation/ItemValidation.java
> +public class ItemValidation {
Исправил.

2023-03-03 13:35 UTC, avan-es commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            throw new ModelValidationException(String.format("Не указан владелиц для '%s'.", item.getName()));
Исправил.

2023-03-03 13:43 UTC, avan-es commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        userValidation.emailIsFree(userDto);
Исправил.

2023-03-03 16:00 UTC, avan-es commented on src/main/java/ru/practicum/shareit/item/model/ItemMapper.java
> +public class ItemMapper {
Исправил.

2023-03-03 16:00 UTC, avan-es commented on src/main/java/ru/practicum/shareit/user/model/UserMapper.java
> +public class UserMapper {
Исправил.

2023-03-04 07:35 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Одно небольшое замечание осталось!

Желаю удачи!

2023-03-04 07:35 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemDto> searchItem(@RequestParam (value = "text") @NotBlank String text) {
Опять, какая-то странность:

1. аннотация `NotBlank`, а потом ты проверяешь `text.isBlank()`. Это всегда `false`
2. переменная называется также, как `value` в `RequestParam`, тогда незачем его явно прописывать

2023-03-05 16:40 UTC, avan-es commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemDto> searchItem(@RequestParam (value = "text") @NotBlank String text) {
Исправил. Пришлось убрать аннотацию @NotBlank. Т.к. если я ставлю её (+ валидацию  @Validated над классом контроллера - это как раз позволяет отработать @NotBlank в RequestParam и убрать проверку в теле на .is.Blank), то тесты в постман не проходят, т.к. требуется пустой лист с item и код 200.

2023-03-06 08:23 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!!!

2023-03-16 16:27 UTC, merged