Add bookings
avan-es/java-shareit pull request #2
Opened 2023-03-26 21:42 UTC by avan-es

Привет!

Закончил ТЗ 14. Высылаю на проверку. Предсказываю много правок🙈

2023-03-27 21:03 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Но есть несколько замечаний, которые необходимо исправить!
Желаю удачи!!!

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                          @RequestParam(name = "state", required = false, defaultValue = "ALL") String state) {
Если есть параметр `defaultValue`, то нет необходимости в `required=false`

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                             @RequestParam(name = "state", required = false, defaultValue = "ALL") String state) {
Надо проверить все места, где эта ошибка может быть

2023-03-27 21:03 UTC, LexLippi commented on src/main/resources/schema.sql
> +    email VARCHAR(512) NOT NULL UNIQUE,
Многовато символов. В `RFC` описано, что электронная почта не может иметь более 320 символов. Так что стоит уменьшить размер колонки:

https://www.rfc-editor.org/errata/eid1690

2023-03-27 21:03 UTC, LexLippi commented on src/main/resources/schema.sql
> +    description VARCHAR NOT NULL,
По возможности лучше всегда ограничивать размер колонок

2023-03-27 21:03 UTC, LexLippi commented on src/main/resources/schema.sql
> +    is_available BOOLEAN DEFAULT TRUE,
`NOT NULL`, наверное, если есть `default value`

2023-03-27 21:03 UTC, LexLippi commented on src/main/resources/schema.sql
> +    status VARCHAR NOT NULL DEFAULT 'WAITING',
тоже лучше ограничить размер колонки

2023-03-27 21:03 UTC, LexLippi commented on src/main/resources/schema.sql
> +    text VARCHAR NOT NULL,
не стоит называть колонки также, как и тип данных. можно заменить на `content`, как вариант

2023-03-27 21:03 UTC, LexLippi commented on src/main/resources/application.properties
> +jdbc.password=root
посмотри, как можно пошифровать эти значения, не стоит их хранить в репозитории в открытом виде.

2023-03-27 21:03 UTC, LexLippi commented on src/main/resources/application-test.properties
> +spring.datasource.password=password
аналогично, посмотри можно ли пошифровать эти значения

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
>                  .contains(user.getEmail())) {
Этот метод выполняется за `O(n)`, где `n` - количество записей в таблице (их может быть очень много), а если будем кидать отдельный запрос в БД, то он будет работать быстрее.

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/dto/UserBookingDto.java
> +@AllArgsConstructor
Точно обе аннотации нужны?

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/validation/ItemValidation.java
>      }
Честно, очень странный метод, целиком :)

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long request;
Не на все колонки есть ограничения, а хотелось бы

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/dto/ItemBookingDto.java
> +@AllArgsConstructor
Точно обе нужны?

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/comment/CommentDto.java
> +@AllArgsConstructor
Аннотации

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/comment/Comment.java
> +    private LocalDateTime created;
Ограничения на колонки

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private String status;
Ограничения на колонки надо проверить

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +        "ORDER BY b.end_date  DESC LIMIT 1 ", nativeQuery = true)
ну уж либо все заглавными, либо наоборот. так как-то странно

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +public interface BookingRepository extends JpaRepository<Booking, Long> {
Есть подозрение, что некоторые запросы можно попытаться объединить. Советую попробовать, если не получится, то можно оставить, как есть

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                return bookingRepository.userFindAllCurrent(userId,  currentDateTime, currentDateTime); //"APPROVED",
Комментарий странный

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        } else {
1. `else` не нужен
2. обычно сначала бросают исключение, а потом возвращают полезный результат

2023-03-27 21:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User booker = new User();
Просто пустая переменная?

2023-03-28 06:47 UTC, avan-es commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                          @RequestParam(name = "state", required = false, defaultValue = "ALL") String state) {
Исправил.

2023-03-28 06:47 UTC, avan-es commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                             @RequestParam(name = "state", required = false, defaultValue = "ALL") String state) {
Исправил.

2023-03-28 06:50 UTC, avan-es commented on src/main/resources/schema.sql
> +    email VARCHAR(512) NOT NULL UNIQUE,
Исправил. Спасибо за ресурс!

2023-03-28 06:59 UTC, avan-es commented on src/main/resources/schema.sql
> +    description VARCHAR NOT NULL,
Ограничил.

2023-03-28 07:01 UTC, avan-es commented on src/main/resources/schema.sql
> +    is_available BOOLEAN DEFAULT TRUE,
Исправил.

2023-03-28 07:05 UTC, avan-es commented on src/main/resources/schema.sql
> +    status VARCHAR NOT NULL DEFAULT 'WAITING',
Готово.

2023-03-28 07:07 UTC, avan-es commented on src/main/resources/schema.sql
> +    text VARCHAR NOT NULL,
Исправил.

2023-03-28 07:32 UTC, avan-es commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User booker = new User();
Она заполняется сразу ниже в ветвлении if-else. Значение зависит от того, кто кинул запрос (пользователь и владелец) и используется в return. Переименовал в нейтральное user (т.к. это не всегда будет booker, может и owner).

2023-03-28 07:35 UTC, avan-es commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        } else {
1. Убрал.
2. Исправил.

2023-03-28 07:36 UTC, avan-es commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                return bookingRepository.userFindAllCurrent(userId,  currentDateTime, currentDateTime); //"APPROVED",
🙈

2023-03-28 07:43 UTC, avan-es commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +        "ORDER BY b.end_date  DESC LIMIT 1 ", nativeQuery = true)
🤦‍♂️. Готово)

2023-03-28 15:57 UTC, avan-es commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
>                  .contains(user.getEmail())) {
Исправил.

2023-03-28 16:18 UTC, avan-es commented on src/main/java/ru/practicum/shareit/user/dto/UserBookingDto.java
> +@AllArgsConstructor
Да. Я использую разные конструкторы в коде. По идеи, аннотация [@Data](https://projectlombok.org/api/lombok/Data) включает в себя аннотацию @RequiredArgsConstructor, но из-за того, что я использую дополнительный конструктор @AllArgsConstructor - он отменяется и нужно его явно указать. 
Я могу убрать обе аннотации и оставить только @Data, но тогда в ru.practicum.shareit.booking.dto.BookingDto.java нужно будет заменить эту строку:

this.booker = new UserBookingDto(bookerId);

Вот этими:
UserBookingDto userBookingDto = new UserBookingDto();
userBookingDto.setId(bookerId);
this.booker = userBookingDto;

Пока оставил как есть, но если скажешь - поменяю. Тебе виднее, как правильнее будет 😊

То же самое и с [src/main/java/ru/practicum/shareit/item/dto/ItemBookingDto.java](https://github.com/avan-es/java-shareit/pull/2/files/0686d0d4fdc0353305da8880ace2ff8eb3410594#diff-d37993fda2ec0853e4ec045c6f29fdc93d0826c709c42afe73507500f267cb16) и [src/main/java/ru/practicum/shareit/item/comment/CommentDto.java](https://github.com/avan-es/java-shareit/pull/2/files/0686d0d4fdc0353305da8880ace2ff8eb3410594#diff-adcdfd3f8af563fe7833f9bbbc8a01abec048d034e8a8383073a2a0e9cf7fcc7)

2023-03-28 16:19 UTC, avan-es commented on src/main/java/ru/practicum/shareit/item/dto/ItemBookingDto.java
> +@AllArgsConstructor
Аналогично с [src/main/java/ru/practicum/shareit/user/dto/UserBookingDto.java](https://github.com/avan-es/java-shareit/pull/2/files/0686d0d4fdc0353305da8880ace2ff8eb3410594#diff-57d3f400364ce35267fc42434157a59bef29e5b6d702c5d6c7c85d0fc477988d)

2023-03-28 16:19 UTC, avan-es commented on src/main/java/ru/practicum/shareit/item/comment/CommentDto.java
> +@AllArgsConstructor
Аналогично с [src/main/java/ru/practicum/shareit/user/dto/UserBookingDto.java](https://github.com/avan-es/java-shareit/pull/2/files/0686d0d4fdc0353305da8880ace2ff8eb3410594#diff-57d3f400364ce35267fc42434157a59bef29e5b6d702c5d6c7c85d0fc477988d)

2023-03-28 17:15 UTC, avan-es commented on src/main/java/ru/practicum/shareit/item/validation/ItemValidation.java
>      }
Согласен 😁. Для чего-то мне нужно было, чтобы он возвращал boolean, но это нигде не используется (видимо что-то пошло не так))). В общем переделал) Теперь метод приличнее стал)

2023-03-28 17:29 UTC, avan-es commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long request;
Добавил ограничения на колонки.

2023-03-28 17:29 UTC, avan-es commented on src/main/java/ru/practicum/shareit/item/comment/Comment.java
> +    private LocalDateTime created;
Добавил ограничения на колонки.

2023-03-28 17:29 UTC, avan-es commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private String status;
Добавил ограничения на колонки.

2023-03-28 17:47 UTC, avan-es commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +public interface BookingRepository extends JpaRepository<Booking, Long> {
Там по 5 запросов для пользователя и владельца - они все разные по условиям в части WHERE. Пробовал основную часть вынести в константу String и к ней добавлять запросы, но так не получается через @Query

2023-03-28 17:52 UTC, avan-es commented on src/main/resources/application.properties
> +jdbc.password=root
Ответил в пачке

2023-03-28 17:52 UTC, avan-es commented on src/main/resources/application-test.properties
> +spring.datasource.password=password
Ответил в пачке

2023-03-29 07:13 UTC, LexLippi requested changes
Привет!

Маленькие правки остались, их надо доделать!

Желаю удачи!

2023-03-29 07:13 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        }
1. Кстати, если первый условный оператор ревертнуть, то сократим уровень вложенности:

```java
if (!item.getOwner().equals(userId)) {
    log.error("Только владелиц может подтвердить бронь.");
    throw new NotFoundException("Только владелиц может подтвердить бронь.");
}
if (approved) {
    booking.setStatus(Status.APPROVED.toString());
} else {
    booking.setStatus(Status.REJECTED.toString());
}
bookingRepository.save(booking);
```

2. Зачем `approved.equals(true)`? Почему не просто `approved`?

2023-03-29 07:13 UTC, LexLippi commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS;
Вот это очень плохая практика, надо стараться обходиться без такого. Вроде должно получаться :)

2023-03-29 09:15 UTC, avan-es commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        }
Исправил) Спасибо! Да, понял про approved 😊

2023-03-29 09:21 UTC, avan-es commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS;
Убрал и залил в Git, но у себя оставил - иначе тесты постмана на один раз)) Постараюсь в дальнейшем убирать эту строку перед коммитами)

2023-03-30 07:21 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!!!

2023-04-05 17:43 UTC, merged