Add item requests
avan-es/java-shareit pull request #3
Opened 2023-04-14 19:13 UTC by avan-es

ТЗ 15.

2023-04-18 07:29 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!
Желаю удачи!

2023-04-18 07:29 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/user/cntroller/UserControllerTest.java
> +    private ObjectMapper objectMapper;
Если ты не используешь модификаторы доступа в тестах (что нормально, так как в них нет необходимости, то стоит не использовать их вообще)

2023-04-18 07:29 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceImplTest.java
> +    PageRequest pageRequest = PageRequest.of(0, 10);
Я не советую делать это полями класса, лучше даже лишний раз что-то скопировать возможно, так как:

1. Работать с изменяемыми переменными куда сложнее, чем с теми, которые ты создал единожды. Не надо думать о том, в каком состоянии они находятся в данный момент, и кто их инициализировал.
2. Читать тестовый код, где сначала идет инициализация данных, потом действия, а потом проверяется их результат, проще чем когда все это в разных местах.

2023-04-18 07:29 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    }*/
Удалить, если не используется

2023-04-18 07:29 UTC, LexLippi commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS;
Это очень плохая команда, стоит попробовать обойтись без нее.
Представь, если при каждом деплое на сервер нашего приложения, мы будем удалять все данные пользователей. Кто будет этим пользоваться тогда?)

2023-04-18 07:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return userDto;
1. А чем тебя так не устраивало?

```java
return UserMapper.INSTANT.toUserDto(userValidation.isPresent(userId));
```
2. Получать объект из `validation`, а не из репозитория - странно

2023-04-18 08:42 UTC, avan-es commented on src/test/java/ru/practicum/shareit/user/cntroller/UserControllerTest.java
> +    private ObjectMapper objectMapper;
Убрал!

2023-04-18 08:50 UTC, avan-es commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return userDto;
1. Это у меня там тест падал, хотел убедиться, что это не из-за этой конструкции)

2. Да, согласен, просто я подумал, что там, где я к валидации этой обращаюсь в БД, следом всегда/почти всегда идет выгрузка пользователя. Ну и чтобы лишний раз не делать запрос в БД, сразу его доставать. Хотя можно, конечно сделать валидацию с параметром true/false - которая будет определять - возвращать ли пользователя - но я не знаю, есть ли в этом смысл?

2023-04-18 20:46 UTC, avan-es commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS;
Да, опять я забыл убрать её перед выгрузкой 🙈

2023-04-18 20:59 UTC, avan-es commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    }*/
Готово!

2023-04-18 21:24 UTC, avan-es commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceImplTest.java
> +    PageRequest pageRequest = PageRequest.of(0, 10);
Привет! Согласен! Попробовал сделать всё внутри тестов - получилось плохо. Вместо 210 строк, получается 600-800 однотипных строк =( решил оставить так, только  PageRequest pageRequest = PageRequest.of(0, 10); перенес).

Пробежался по всем тестам - где что можно было вставить в тесты - вставил.

2023-04-18 21:26 UTC, avan-es commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS;
Вернул обратно - без нее тесты на Git-е не проходят тоже. Раньше проходили (на предыдущих ТЗ).  Но про то, то это плохая практика - понимаю и полностью согласен!

2023-04-19 08:26 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2023-04-23 12:40 UTC, merged