Add docker
avan-es/java-shareit pull request #4
Opened 2023-04-26 11:59 UTC by avan-es

2023-04-28 07:01 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть несколько замечаний, которые необходио исправить!

Желаю удачи!

2023-04-28 07:01 UTC, LexLippi commented on docker-compose.yml
> +      #- TZ=Europe/Moscow
Не оставляем такие комменты

2023-04-28 07:01 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +		return Optional.empty();
Можно изящнее переписать с помощью `Stream API`:

```java
return Arrays.stream(BookingState.values())
                     .filter(state -> state.name().equalsIgnoreCase(stringState))
                     .findFirst();
```

2023-04-28 07:01 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                    @RequestParam(value = "from", defaultValue = "0") @Min(0) Integer from,
Мне кажется в таком случае лучше `@PositiveOrZero`

2023-04-28 07:01 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    }
Это можно изящнее переписать с помощью регулярных выражений. Подумай как.

2023-04-28 07:01 UTC, LexLippi commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +//        }
Удаляем, если не нужно

2023-04-28 07:01 UTC, LexLippi commented on server/src/main/resources/application.properties
> +##spring.datasource.password=test
удаляем, если не нужно

2023-04-28 15:38 UTC, avan-es commented on docker-compose.yml
> +      #- TZ=Europe/Moscow
Готово!

2023-04-28 15:48 UTC, avan-es commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +		return Optional.empty();
Спасибо! Исправил!

2023-04-28 16:03 UTC, avan-es commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                    @RequestParam(value = "from", defaultValue = "0") @Min(0) Integer from,
Готово)

2023-04-28 16:07 UTC, avan-es commented on server/src/main/resources/application.properties
> +##spring.datasource.password=test
Убрал лишнее, оставил небольшой кусок, который мне нужен для локального запуска сервера, что его дебажить

2023-04-28 16:19 UTC, avan-es commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +//        }
Пропустил - раскомментировал) Спасибо!

2023-04-28 17:07 UTC, avan-es commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    }
Спасибо!!! Заменил этот метод одной строкой: user.getEmail().replaceAll("(?<=.{2}).(?=[^@]*?@)", "*") - колдовство)

2023-04-29 15:04 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!!!

2023-05-03 07:58 UTC, merged